# ============================================================
# Makefile para cross-compilación Raspberry Pi 4 ARM64
# usando el toolchain AArch64 instalado en el sistema
# ============================================================

CXX_CROSS = aarch64-linux-gnu-g++

CXXFLAGS = -std=c++11 -ggdb3 -O0 -Wall -Wextra -pedantic

# Directorios
SRC_DIR     = src
BIN_DIR     = bin
RESULTS_DIR = results

# Archivos
SRC        = $(SRC_DIR)/sensor_data_processing.cpp
TARGET_RPI = $(BIN_DIR)/sensor_rpi_sysroot

.PHONY: rpi directories clean

rpi: directories $(TARGET_RPI)

directories:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(RESULTS_DIR)/callgrind
	@mkdir -p $(RESULTS_DIR)/massif

$(TARGET_RPI): $(SRC)
	$(CXX_CROSS) $(CXXFLAGS) \
		-o $@ $<

clean:
	rm -f $(TARGET_RPI)
