# ============================================================
# Makefile para cross-compilación Raspberry Pi 4 ARM64
# usando sysroot Debian 12 / glibc 2.36
# ============================================================

CXX_CROSS = aarch64-linux-gnu-g++

CXXFLAGS = -std=c++11 -ggdb3 -O0 -Wall -Wextra -pedantic

# Sysroot Debian 12 ARM64
SYSROOT = /opt/lab2-sysroot

# Enlace
LDFLAGS_RPI = -L$(SYSROOT)/usr/lib/aarch64-linux-gnu -l:libstdc++.so.6

# Directorios
SRC_DIR     = src
BIN_DIR     = bin
RESULTS_DIR = results

# Archivos
SRC        = $(SRC_DIR)/sensor_data_processing.cpp
TARGET_RPI = $(BIN_DIR)/sensor_rpi_sysroot

.PHONY: rpi directories clean

rpi: directories $(TARGET_RPI)

directories:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(RESULTS_DIR)/callgrind
	@mkdir -p $(RESULTS_DIR)/massif

$(TARGET_RPI): $(SRC)
	$(CXX_CROSS) $(CXXFLAGS) \
		--sysroot=$(SYSROOT) \
		-nostdinc++ \
		-isystem $(SYSROOT)/usr/include/c++/12 \
		-isystem $(SYSROOT)/usr/include/aarch64-linux-gnu/c++/12 \
		-isystem /usr/include \
		-isystem $(SYSROOT)/usr/include/aarch64-linux-gnu \
		-isystem $(SYSROOT)/usr/include \
		-L$(SYSROOT)/usr/lib/aarch64-linux-gnu \
		-Wl,-rpath-link,$(SYSROOT)/usr/lib/aarch64-linux-gnu \
		-o $@ $< \
		$(LDFLAGS_RPI)

clean:
	rm -f $(TARGET_RPI)
